################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
examples/platforms/utils/debug_uart.obj: /home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/examples/platforms/utils/debug_uart.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/home/yigit/opt/CCS/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 -me -O4 --opt_for_speed=0 --include_path="/home/yigit/FreeZone/Thread/01-Lab1/libopenthread_platform_utils_ftd_CC26X2R1_LAUNCHXL_ccs" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/examples/platforms" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source" --include_path="/home/yigit/FreeZone/Thread/01-Lab1/libmbedcrypto_CC26X2R1_LAUNCHXL_ccs" --include_path="/home/yigit/FreeZone/Thread/01-Lab1/libopenthread_ftd_CC26X2R1_LAUNCHXL_ccs" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/third_party/mbedtls" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/third_party/mbedtls/repo.patched/include" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/src/core" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/src" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/include" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/etc/ti/CC26X2R1_LAUNCHXL/ccs" --include_path="/home/yigit/opt/CCS/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=SIMPLELINK_OPENTHREAD_SDK_BUILD=1 --define=SIMPLELINK_OPENTHREAD_CONFIG_FTD=1 --define=SIMPLELINK_OPENTHREAD_CONFIG_CC2652=1 --define=OPENTHREAD_CONFIG_FILE='"openthread-config-cc2652-ccs-ftd.h"' --define=OPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc2652-config-ide.h"' --define=MBEDTLS_CONFIG_FILE='"mbedtls-config-cc2652-ccs.h"' --define=HAVE_CONFIG_H --define=_BSD_SOURCE=1 --define=_DEFAULT_SOURCE=1 --define=OPENTHREAD_FTD=1 --c99 --float_operations_allowed=none --plain_char=unsigned --gcc --printf_support=nofloat --diag_suppress=23000 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --embedded_constants=on --enum_type=packed --wchar_t=16 --abi=eabi --common=on --preproc_with_compile --preproc_dependency="examples/platforms/utils/debug_uart.d_raw" --obj_directory="examples/platforms/utils" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

examples/platforms/utils/settings.obj: /home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/examples/platforms/utils/settings.cpp $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/home/yigit/opt/CCS/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 -me -O4 --opt_for_speed=0 --include_path="/home/yigit/FreeZone/Thread/01-Lab1/libopenthread_platform_utils_ftd_CC26X2R1_LAUNCHXL_ccs" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/examples/platforms" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source" --include_path="/home/yigit/FreeZone/Thread/01-Lab1/libmbedcrypto_CC26X2R1_LAUNCHXL_ccs" --include_path="/home/yigit/FreeZone/Thread/01-Lab1/libopenthread_ftd_CC26X2R1_LAUNCHXL_ccs" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/third_party/mbedtls" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/third_party/mbedtls/repo.patched/include" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/src/core" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/src" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/include" --include_path="/home/yigit/ti/ti/simplelink_cc26x2_sdk_2_10_00_44/source/third_party/openthread/etc/ti/CC26X2R1_LAUNCHXL/ccs" --include_path="/home/yigit/opt/CCS/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=SIMPLELINK_OPENTHREAD_SDK_BUILD=1 --define=SIMPLELINK_OPENTHREAD_CONFIG_FTD=1 --define=SIMPLELINK_OPENTHREAD_CONFIG_CC2652=1 --define=OPENTHREAD_CONFIG_FILE='"openthread-config-cc2652-ccs-ftd.h"' --define=OPENTHREAD_PROJECT_CORE_CONFIG_FILE='"openthread-core-cc2652-config-ide.h"' --define=MBEDTLS_CONFIG_FILE='"mbedtls-config-cc2652-ccs.h"' --define=HAVE_CONFIG_H --define=_BSD_SOURCE=1 --define=_DEFAULT_SOURCE=1 --define=OPENTHREAD_FTD=1 --c99 --float_operations_allowed=none --plain_char=unsigned --gcc --printf_support=nofloat --diag_suppress=23000 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --embedded_constants=on --enum_type=packed --wchar_t=16 --abi=eabi --common=on --preproc_with_compile --preproc_dependency="examples/platforms/utils/settings.d_raw" --obj_directory="examples/platforms/utils" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '


